// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=./usecase_mock.go -package=user
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	skinport "github.com/madkingxxx/backend-test/internal/core/skinport"
	user "github.com/madkingxxx/backend-test/internal/core/user"
	gomock "go.uber.org/mock/gomock"
)

// MockuserServiceI is a mock of userServiceI interface.
type MockuserServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceIMockRecorder
	isgomock struct{}
}

// MockuserServiceIMockRecorder is the mock recorder for MockuserServiceI.
type MockuserServiceIMockRecorder struct {
	mock *MockuserServiceI
}

// NewMockuserServiceI creates a new mock instance.
func NewMockuserServiceI(ctrl *gomock.Controller) *MockuserServiceI {
	mock := &MockuserServiceI{ctrl: ctrl}
	mock.recorder = &MockuserServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserServiceI) EXPECT() *MockuserServiceIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockuserServiceI) Get(ctx context.Context, id int) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockuserServiceIMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockuserServiceI)(nil).Get), ctx, id)
}

// TopUp mocks base method.
func (m *MockuserServiceI) TopUp(ctx context.Context, id int, amount float64) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUp", ctx, id, amount)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopUp indicates an expected call of TopUp.
func (mr *MockuserServiceIMockRecorder) TopUp(ctx, id, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUp", reflect.TypeOf((*MockuserServiceI)(nil).TopUp), ctx, id, amount)
}

// Withdraw mocks base method.
func (m *MockuserServiceI) Withdraw(ctx context.Context, id int, amount float64) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, id, amount)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockuserServiceIMockRecorder) Withdraw(ctx, id, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockuserServiceI)(nil).Withdraw), ctx, id, amount)
}

// MockskinportServiceI is a mock of skinportServiceI interface.
type MockskinportServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockskinportServiceIMockRecorder
	isgomock struct{}
}

// MockskinportServiceIMockRecorder is the mock recorder for MockskinportServiceI.
type MockskinportServiceIMockRecorder struct {
	mock *MockskinportServiceI
}

// NewMockskinportServiceI creates a new mock instance.
func NewMockskinportServiceI(ctrl *gomock.Controller) *MockskinportServiceI {
	mock := &MockskinportServiceI{ctrl: ctrl}
	mock.recorder = &MockskinportServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockskinportServiceI) EXPECT() *MockskinportServiceIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockskinportServiceI) Get(ctx context.Context, hashName string) (skinport.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, hashName)
	ret0, _ := ret[0].(skinport.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockskinportServiceIMockRecorder) Get(ctx, hashName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockskinportServiceI)(nil).Get), ctx, hashName)
}
